// based on file generated by create-electron-app with option --template=webpack

module.exports = [
    // https://github.com/electron-userland/electron-forge/issues/1688
    {
        test: /\.(m?js|node)$/,
        parser: { amd: false },
        use: {
            // fork of zeit/webpack-asset-relocator-loader with some fixes that we need
            // create-electron-app included this one by default, next to another one that we removed because of GitHub issue linked above
            loader: "@marshallofsound/webpack-asset-relocator-loader",
            options: {
                outputAssetBase: "native_modules",
            },
        },
    },
    {
        test: /\.svg$/,
        use: {
            loader: "svg-url-loader",
            options: {
                encoding: "base64",
            },
        },
    },
];
