// based on file generated by create-electron-app with option --template=webpack

const LicenseWebpackPlugin = require("license-webpack-plugin").LicenseWebpackPlugin;
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
    entry: "./src/main/main.js",
    module: {
        rules: require("./webpack.rules"),
    },
    plugins: [
        new LicenseWebpackPlugin(),
        new CopyPlugin({
            patterns: ["LICENSE"],
        }),
    ],
};
